// Multiple choice — shared by the PC and Android apps, and by the test harness
// via require().
//
// Two halves, and the split matters:
//
//   * The pure half (`buildChoices` and the LaTeX comparison helpers) runs under
//     Node with no DOM, which is what lets tools/check-practice.js hammer every
//     template a few hundred times and catch a distractor that is secretly right.
//   * The view half no-ops unless `#choices` is on the page, the same way
//     practice-quiz.js no-ops without `#startQuiz`.
//
// Distractors are declared per template in practice-data.js, never generated by
// mutating the answer string. Answers here come in four structurally different
// shapes — bare scalars, labelled (`x = -3`), multi-value (`x = 30°, 150°`) and
// expressions carrying furniture (`+ C`, `\quad x \ne 3`) — and string-mutating
// any of those produces options that give themselves away.

/** How many options a question offers. The mastery model discounts 1/k of it. */
const MCQ_OPTIONS = 4;

/**
 * A form of a LaTeX string suitable for *comparison only* — never for display.
 *
 * The point is that two options which render identically must compare equal,
 * otherwise `x^{3}` and `x^3` both appear, one of them marked wrong.
 */
function baseNormal(s) {
  return String(s == null ? '' : s)
    .replace(/\\left|\\right/g, '')
    .replace(/\\[tdc]frac/g, '\\frac')
    .replace(/\\!|\\,|\\;|\\:|\\quad|\\qquad/g, ' ')
    .replace(/\s+/g, '')
    .trim();
}

/** Braces around a single token are decoration: \sqrt{9} renders as \sqrt9. */
const stripSoloBraces = (s) => s.replace(/\{([\w#])\}/g, '$1');

function normalLatex(s) {
  return stripSoloBraces(baseNormal(s));
}

/**
 * Every number in a LaTeX string, signed and sorted — the multiset used to spot
 * permutations.
 *
 * Runs on the whitespace-stripped form deliberately. PR.s writes a negative as
 * "- 8", with a space, and on the raw string the minus would not attach to the
 * 8 — so "(x + 2)^2 - 8" and "(x - 2)^2 - 8" would both read as {2, 2, 8} and
 * every sign-flipped distractor would be thrown away as a reordering.
 */
function numbersIn(s) {
  return (baseNormal(s).match(/-?\d+(?:\.\d+)?/g) || [])
    .map(Number)
    .sort((a, b) => a - b);
}

/**
 * What's left of an option once every number is removed: the LaTeX structure.
 *
 * This exists to catch the option that gives itself away without any maths —
 * three of the form `x = n` and one a fraction, three carrying `+ C` and one
 * not, three with an x term and one where it vanished.
 *
 * Signs and the numbers themselves go too, deliberately. A student cannot tell
 * which option is right from "+ 3" versus "- 3", and varying a sign is most of
 * what a good distractor does. Dropping the digits also means "+ x" (a unit
 * coefficient, which PR.xt prints without its 1) matches "- 19x", and
 * \sqrt{9} matches \sqrt{89}.
 */
function shapeOf(s) {
  return baseNormal(s)
    .replace(/[+-]?\d+(?:\.\d+)?/g, '')
    .replace(/[+-]/g, ''); // a bare sign is left by a unit coefficient: "- x"
}

function sameNumbers(a, b) {
  const x = numbersIn(a);
  const y = numbersIn(b);
  return x.length === y.length && x.every((v, i) => v === y[i]);
}

/**
 * Is `candidate` secretly the same answer as `answer`?
 *
 * Beyond plain equality this catches the reordering trap: `x = 3, \ x = -5` and
 * `x = -5, \ x = 3` are the same answer to a quadratic, and a student who picks
 * the "wrong" one has been marked down for being right. Same shape plus the same
 * multiset of numbers means the two differ only by ordering.
 *
 * That test is on by default because the two failures are not symmetric — a
 * false positive costs one candidate, a false negative marks a student wrong for
 * being right. But it is wrong wherever position carries meaning: in a partial
 * fraction the numerators sit over particular denominators, and in `|z| = 5,
 * arg = 53` the two numbers are different quantities. Those templates set
 * `mcqOrdered: true`, which turns the reordering test off and puts the
 * responsibility back on the author never to write a distractor that is the
 * answer rearranged.
 */
function equivalentAnswers(candidate, answer, ordered) {
  const a = normalLatex(candidate);
  const b = normalLatex(answer);
  if (a === b) return true;
  if (ordered) return false;
  if (shapeOf(candidate) !== shapeOf(answer)) return false;
  return numbersIn(answer).length > 1 && sameNumbers(candidate, answer);
}

/** Every number in reading order — unlike numbersIn, which sorts them. */
function numbersInOrder(s) {
  return (baseNormal(s).match(/-?\d+(?:\.\d+)?/g) || []).map(Number);
}

const NUM_WORDS = {
  zero: 0, one: 1, two: 2, three: 3, four: 4, five: 5, six: 6, seven: 7, eight: 8,
  nine: 9, ten: 10, eleven: 11, twelve: 12, thirteen: 13, fourteen: 14, fifteen: 15,
  sixteen: 16, seventeen: 17, eighteen: 18, nineteen: 19, twenty: 20, thirty: 30,
  forty: 40, fifty: 50, sixty: 60, seventy: 70, eighty: 80, ninety: 90,
};

/**
 * Turn spoken numbers into digits so a transcript can be compared with LaTeX:
 * "x equals minus twenty three" becomes "x equals -23".
 *
 * This exists because without it almost every spoken answer returns `unsure` —
 * the transcript has no digits in it at all — and every `unsure` costs an API
 * call. It handles the range a maths answer actually lands in: units, teens,
 * tens, "hundred" as a multiplier, decimals said as "point five", and a leading
 * "minus" or "negative". Anything past that is left alone for `markAnswer` to
 * escalate, which is the correct outcome for something we cannot read.
 */
function digitiseSpokenNumbers(text) {
  const tokens = String(text).split(/\b/);
  const out = [];
  let acc = null;        // the number being assembled
  let negate = false;
  const flush = () => {
    if (acc != null) out.push(String(negate ? -acc : acc));
    acc = null;
    negate = false;
  };
  for (const tok of tokens) {
    const w = tok.trim().toLowerCase();
    if (!w) { if (acc == null) out.push(tok); continue; }
    if (w === 'minus' || w === 'negative') { flush(); negate = true; continue; }
    if (w === 'hundred' && acc != null) { acc *= 100; continue; }
    if (w === 'and' && acc != null) continue;   // "a hundred and five"
    if (Object.prototype.hasOwnProperty.call(NUM_WORDS, w)) {
      const v = NUM_WORDS[w];
      // 20 + 3 composes; 3 then 4 does not — flush and start again.
      if (acc == null) acc = v;
      else if (acc % 10 === 0 && v < 10) acc += v;
      else { flush(); acc = v; }
      continue;
    }
    if (w === 'point' && acc != null) {
      // "three point five" — collect the digits that follow as decimals.
      out.push(String(negate ? -acc : acc));
      acc = null; negate = false;
      out.push('.');
      continue;
    }
    flush();
    if (negate) { out.push('-'); negate = false; }
    out.push(tok);
  }
  flush();
  if (negate) out.push('-');
  return out.join('');
}

/**
 * Mark a free-text or spoken answer against the stored one, offline and for
 * nothing. This is what lets the voice tutor say whether you were right without
 * ever being told what right was, and it is the default path — only `unsure`
 * costs an API call.
 *
 * Deliberately NOT a speech-to-LaTeX parser. Comparing the numbers each side
 * actually contains is what makes "x equals two, y equals three" line up with
 * `x = 2, \ y = 3` without pretending to understand English.
 *
 * Three rules earn their place:
 *
 *   * `equivalentAnswers` is called with `ordered: true`. The unordered branch
 *     treats the same numbers in any order as the same answer — correct for the
 *     two roots of a quadratic, badly wrong here, where it would pass
 *     "x = 3, y = 2" as "x = 2, y = 3".
 *   * numbers are compared IN ORDER for the same reason.
 *   * a different COUNT of numbers returns `unsure`, not `wrong`. "0.5" against
 *     \frac{1}{2} is one number against two: the two are written differently
 *     rather than disagreeing, and claiming a student got that wrong is worse
 *     than admitting we cannot tell.
 */
function markAnswer(heard, answer) {
  // A transcript says "two", not "2", and without this every spoken answer
  // returns unsure and costs an API call.
  const said = digitiseSpokenNumbers(String(heard == null ? '' : heard)).trim();
  const truth = String(answer == null ? '' : answer).trim();
  if (!said) return { verdict: 'unsure', why: 'nothing heard' };
  if (!truth) return { verdict: 'unsure', why: 'no stored answer' };

  if (normalLatex(said) === normalLatex(truth)) return { verdict: 'right', why: 'said it exactly' };
  if (equivalentAnswers(said, truth, true)) return { verdict: 'right', why: 'same answer, written differently' };

  const a = numbersInOrder(said);
  const b = numbersInOrder(truth);
  if (!a.length || !b.length) return { verdict: 'unsure', why: 'no numbers to compare' };
  if (a.length !== b.length) return { verdict: 'unsure', why: 'counted a different number of values' };
  const same = a.every((n, i) => Math.abs(n - b[i]) < 1e-9);
  return same
    ? { verdict: 'right', why: 'every value matches, in order' }
    : { verdict: 'wrong', why: 'the values do not match' };
}

/**
 * Assemble one question's options, or null if it can't be done honestly.
 *
 * `distractorsFn(w)` receives the generator's workings bag and returns candidates
 * best-first — 4 to 6 of them, so this has slack to throw some away. Returning
 * null (too few survivors, no distractors declared, a thrown distractor) means
 * the question falls back to self-marking, which the caller handles.
 *
 * `rand` is injectable so the harness can make a run reproducible.
 */
function buildChoices(answer, distractorsFn, w, opts) {
  if (typeof distractorsFn !== 'function') return null;
  const { rand, ordered } = opts || {};
  const random = rand || Math.random;

  let candidates;
  try {
    candidates = distractorsFn(w) || [];
  } catch {
    return null; // a broken distractor must never take the question down with it
  }
  if (!Array.isArray(candidates)) return null;

  const kept = [];
  const seen = new Set([normalLatex(answer)]);
  for (const c of candidates) {
    if (!c || !c.latex) continue;
    const norm = normalLatex(c.latex);
    if (seen.has(norm)) continue;              // duplicate of the answer or of each other
    if (equivalentAnswers(c.latex, answer, ordered)) continue; // answer in disguise
    seen.add(norm);
    kept.push({ latex: String(c.latex), why: c.why || null });
    if (kept.length === MCQ_OPTIONS - 1) break;
  }
  if (kept.length < MCQ_OPTIONS - 1) return null;

  // Never ship a 3-option question: it's a 33% guess floor being scored as if it
  // were 25%, which inflates the bar exactly the way the correction exists to stop.
  const options = [{ latex: String(answer), why: null }, ...kept];
  for (let i = options.length - 1; i > 0; i--) {
    const j = Math.floor(random() * (i + 1));
    [options[i], options[j]] = [options[j], options[i]];
  }
  return {
    options,
    answerIndex: options.findIndex((o) => o.why === null),
    k: options.length,
  };
}

// ---- View ---------------------------------------------------------------------------
//
// Reuses globals from practice.js (tex, current, recordAttempt, advance,
// answerMode, revealed) — classic script tags share one top-level scope.

const HAS_DOM = typeof document !== 'undefined';
const mcqEl = HAS_DOM ? document.getElementById('choices') : null;
const mcqFeedbackEl = HAS_DOM ? document.getElementById('mcqFeedback') : null;
const mcqNextEl = HAS_DOM ? document.getElementById('mcqNext') : null;

let mcqPicked = false;

/** Wipe the option grid. Called from practice.js on every new question. */
function mcqClear() {
  if (!mcqEl) return;
  mcqPicked = false;
  mcqEl.innerHTML = '';
  mcqEl.classList.add('hidden');
  if (mcqFeedbackEl) {
    mcqFeedbackEl.textContent = '';
    mcqFeedbackEl.className = 'mcq-feedback hidden';
  }
  if (mcqNextEl) mcqNextEl.classList.add('hidden');
}

/**
 * Draw the options for the current question, if there are any and we're in
 * multiple-choice mode. Returns true if the grid took over the answering.
 */
function mcqShow(item) {
  if (!mcqEl) return false;
  mcqClear();
  if (!item || !item.choices || !item.choices.options) return false;

  for (let i = 0; i < item.choices.options.length; i++) {
    const opt = item.choices.options[i];
    // A <div>, not a <button>: applyPaper injects `select,button{...!important}`
    // from Kotlin on every paper-colour change, which would repaint the
    // right/wrong states back to plain and destroy the only feedback signal.
    const cell = document.createElement('div');
    cell.className = 'mcq-option';
    cell.setAttribute('role', 'button');
    cell.setAttribute('tabindex', '0');
    cell.dataset.index = String(i);
    const body = document.createElement('span');
    tex(body, opt.latex, false);
    cell.appendChild(body);
    cell.addEventListener('click', () => mcqPick(i));
    cell.addEventListener('keydown', (e) => {
      if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); mcqPick(i); }
    });
    mcqEl.appendChild(cell);
  }
  mcqEl.classList.remove('hidden');
  return true;
}

/** Handle a pick: lock everything, mark it, explain the slip, record it. */
function mcqPick(index) {
  if (mcqPicked || !current || !current.choices) return;
  mcqPicked = true;

  const { options, answerIndex, k } = current.choices;
  const right = index === answerIndex;
  const chosen = options[index];

  for (const cell of mcqEl.querySelectorAll('.mcq-option')) {
    const i = Number(cell.dataset.index);
    cell.classList.add('locked');
    cell.setAttribute('tabindex', '-1');
    if (i === answerIndex) cell.classList.add('correct');
    else if (i === index) cell.classList.add('wrong');
  }

  if (mcqFeedbackEl) {
    mcqFeedbackEl.className = 'mcq-feedback ' + (right ? 'good' : 'bad');
    mcqFeedbackEl.textContent = right
      ? 'Correct.'
      : explain(chosen && chosen.why);
  }
  if (mcqNextEl) mcqNextEl.classList.remove('hidden');

  // Reading the steps first turns an objectively-graded question into a copying
  // exercise, so it doesn't get objective credit. `attemptFrom`'s docstring
  // already reserves 0.5 for "right after a hint".
  const peeked = typeof revealed === 'number' && revealed > 0;
  if (peeked) {
    recordAttempt(right ? 0.5 : 0, 'self', {});
  } else {
    recordAttempt(right ? 1 : 0, 'mcq', { k, miss: right ? null : (chosen && chosen.why) });
  }

  // The worked steps are the reward for having answered, either way.
  enableReveal();
}

/** The sentence for a wrong pick, or a plain fallback if none was declared. */
function explain(why) {
  const entry = why && typeof MISCONCEPTIONS !== 'undefined' ? MISCONCEPTIONS[why] : null;
  return entry && entry.hint
    ? entry.hint
    : 'Not quite — reveal the steps to see where it goes.';
}

if (mcqNextEl) {
  mcqNextEl.addEventListener('click', () => {
    if (typeof advance === 'function') advance();
  });
}

if (typeof module !== 'undefined' && module.exports) {
  module.exports = {
    MCQ_OPTIONS, buildChoices, normalLatex, numbersIn, numbersInOrder, shapeOf,
    equivalentAnswers, markAnswer,
  };
}
