// Multiple choice — shared by the PC and Android apps, and by the test harness
// via require().
//
// Two halves, and the split matters:
//
//   * The pure half (`buildChoices` and the LaTeX comparison helpers) runs under
//     Node with no DOM, which is what lets tools/check-practice.js hammer every
//     template a few hundred times and catch a distractor that is secretly right.
//   * The view half no-ops unless `#choices` is on the page, the same way
//     practice-quiz.js no-ops without `#startQuiz`.
//
// Distractors are declared per template in practice-data.js, never generated by
// mutating the answer string. Answers here come in four structurally different
// shapes — bare scalars, labelled (`x = -3`), multi-value (`x = 30°, 150°`) and
// expressions carrying furniture (`+ C`, `\quad x \ne 3`) — and string-mutating
// any of those produces options that give themselves away.

/** How many options a question offers. The mastery model discounts 1/k of it. */
const MCQ_OPTIONS = 4;

/**
 * A form of a LaTeX string suitable for *comparison only* — never for display.
 *
 * The point is that two options which render identically must compare equal,
 * otherwise `x^{3}` and `x^3` both appear, one of them marked wrong.
 */
function baseNormal(s) {
  return String(s == null ? '' : s)
    .replace(/\\left|\\right/g, '')
    .replace(/\\[tdc]frac/g, '\\frac')
    .replace(/\\!|\\,|\\;|\\:|\\quad|\\qquad/g, ' ')
    .replace(/\s+/g, '')
    .trim();
}

/** Braces around a single token are decoration: \sqrt{9} renders as \sqrt9. */
const stripSoloBraces = (s) => s.replace(/\{([\w#])\}/g, '$1');

function normalLatex(s) {
  return stripSoloBraces(baseNormal(s));
}

/**
 * Every number in a LaTeX string, signed and sorted — the multiset used to spot
 * permutations.
 *
 * Runs on the whitespace-stripped form deliberately. PR.s writes a negative as
 * "- 8", with a space, and on the raw string the minus would not attach to the
 * 8 — so "(x + 2)^2 - 8" and "(x - 2)^2 - 8" would both read as {2, 2, 8} and
 * every sign-flipped distractor would be thrown away as a reordering.
 */
function numbersIn(s) {
  return (baseNormal(s).match(/-?\d+(?:\.\d+)?/g) || [])
    .map(Number)
    .sort((a, b) => a - b);
}

/**
 * What's left of an option once every number is removed: the LaTeX structure.
 *
 * This exists to catch the option that gives itself away without any maths —
 * three of the form `x = n` and one a fraction, three carrying `+ C` and one
 * not, three with an x term and one where it vanished.
 *
 * Signs and the numbers themselves go too, deliberately. A student cannot tell
 * which option is right from "+ 3" versus "- 3", and varying a sign is most of
 * what a good distractor does. Dropping the digits also means "+ x" (a unit
 * coefficient, which PR.xt prints without its 1) matches "- 19x", and
 * \sqrt{9} matches \sqrt{89}.
 */
function shapeOf(s) {
  return baseNormal(s)
    .replace(/[+-]?\d+(?:\.\d+)?/g, '')
    .replace(/[+-]/g, ''); // a bare sign is left by a unit coefficient: "- x"
}

function sameNumbers(a, b) {
  const x = numbersIn(a);
  const y = numbersIn(b);
  return x.length === y.length && x.every((v, i) => v === y[i]);
}

/**
 * Is `candidate` secretly the same answer as `answer`?
 *
 * Beyond plain equality this catches the reordering trap: `x = 3, \ x = -5` and
 * `x = -5, \ x = 3` are the same answer to a quadratic, and a student who picks
 * the "wrong" one has been marked down for being right. Same shape plus the same
 * multiset of numbers means the two differ only by ordering.
 *
 * That test is on by default because the two failures are not symmetric — a
 * false positive costs one candidate, a false negative marks a student wrong for
 * being right. But it is wrong wherever position carries meaning: in a partial
 * fraction the numerators sit over particular denominators, and in `|z| = 5,
 * arg = 53` the two numbers are different quantities. Those templates set
 * `mcqOrdered: true`, which turns the reordering test off and puts the
 * responsibility back on the author never to write a distractor that is the
 * answer rearranged.
 */
function equivalentAnswers(candidate, answer, ordered) {
  const a = normalLatex(candidate);
  const b = normalLatex(answer);
  if (a === b) return true;
  if (ordered) return false;
  if (shapeOf(candidate) !== shapeOf(answer)) return false;
  return numbersIn(answer).length > 1 && sameNumbers(candidate, answer);
}

/**
 * Assemble one question's options, or null if it can't be done honestly.
 *
 * `distractorsFn(w)` receives the generator's workings bag and returns candidates
 * best-first — 4 to 6 of them, so this has slack to throw some away. Returning
 * null (too few survivors, no distractors declared, a thrown distractor) means
 * the question falls back to self-marking, which the caller handles.
 *
 * `rand` is injectable so the harness can make a run reproducible.
 */
function buildChoices(answer, distractorsFn, w, opts) {
  if (typeof distractorsFn !== 'function') return null;
  const { rand, ordered } = opts || {};
  const random = rand || Math.random;

  let candidates;
  try {
    candidates = distractorsFn(w) || [];
  } catch {
    return null; // a broken distractor must never take the question down with it
  }
  if (!Array.isArray(candidates)) return null;

  const kept = [];
  const seen = new Set([normalLatex(answer)]);
  for (const c of candidates) {
    if (!c || !c.latex) continue;
    const norm = normalLatex(c.latex);
    if (seen.has(norm)) continue;              // duplicate of the answer or of each other
    if (equivalentAnswers(c.latex, answer, ordered)) continue; // answer in disguise
    seen.add(norm);
    kept.push({ latex: String(c.latex), why: c.why || null });
    if (kept.length === MCQ_OPTIONS - 1) break;
  }
  if (kept.length < MCQ_OPTIONS - 1) return null;

  // Never ship a 3-option question: it's a 33% guess floor being scored as if it
  // were 25%, which inflates the bar exactly the way the correction exists to stop.
  const options = [{ latex: String(answer), why: null }, ...kept];
  for (let i = options.length - 1; i > 0; i--) {
    const j = Math.floor(random() * (i + 1));
    [options[i], options[j]] = [options[j], options[i]];
  }
  return {
    options,
    answerIndex: options.findIndex((o) => o.why === null),
    k: options.length,
  };
}

// ---- View ---------------------------------------------------------------------------
//
// Reuses globals from practice.js (tex, current, recordAttempt, advance,
// answerMode, revealed) — classic script tags share one top-level scope.

const HAS_DOM = typeof document !== 'undefined';
const mcqEl = HAS_DOM ? document.getElementById('choices') : null;
const mcqFeedbackEl = HAS_DOM ? document.getElementById('mcqFeedback') : null;
const mcqNextEl = HAS_DOM ? document.getElementById('mcqNext') : null;

let mcqPicked = false;

/** Wipe the option grid. Called from practice.js on every new question. */
function mcqClear() {
  if (!mcqEl) return;
  mcqPicked = false;
  mcqEl.innerHTML = '';
  mcqEl.classList.add('hidden');
  if (mcqFeedbackEl) {
    mcqFeedbackEl.textContent = '';
    mcqFeedbackEl.className = 'mcq-feedback hidden';
  }
  if (mcqNextEl) mcqNextEl.classList.add('hidden');
}

/**
 * Draw the options for the current question, if there are any and we're in
 * multiple-choice mode. Returns true if the grid took over the answering.
 */
function mcqShow(item) {
  if (!mcqEl) return false;
  mcqClear();
  if (!item || !item.choices || !item.choices.options) return false;

  for (let i = 0; i < item.choices.options.length; i++) {
    const opt = item.choices.options[i];
    // A <div>, not a <button>: applyPaper injects `select,button{...!important}`
    // from Kotlin on every paper-colour change, which would repaint the
    // right/wrong states back to plain and destroy the only feedback signal.
    const cell = document.createElement('div');
    cell.className = 'mcq-option';
    cell.setAttribute('role', 'button');
    cell.setAttribute('tabindex', '0');
    cell.dataset.index = String(i);
    const body = document.createElement('span');
    tex(body, opt.latex, false);
    cell.appendChild(body);
    cell.addEventListener('click', () => mcqPick(i));
    cell.addEventListener('keydown', (e) => {
      if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); mcqPick(i); }
    });
    mcqEl.appendChild(cell);
  }
  mcqEl.classList.remove('hidden');
  return true;
}

/** Handle a pick: lock everything, mark it, explain the slip, record it. */
function mcqPick(index) {
  if (mcqPicked || !current || !current.choices) return;
  mcqPicked = true;

  const { options, answerIndex, k } = current.choices;
  const right = index === answerIndex;
  const chosen = options[index];

  for (const cell of mcqEl.querySelectorAll('.mcq-option')) {
    const i = Number(cell.dataset.index);
    cell.classList.add('locked');
    cell.setAttribute('tabindex', '-1');
    if (i === answerIndex) cell.classList.add('correct');
    else if (i === index) cell.classList.add('wrong');
  }

  if (mcqFeedbackEl) {
    mcqFeedbackEl.className = 'mcq-feedback ' + (right ? 'good' : 'bad');
    mcqFeedbackEl.textContent = right
      ? 'Correct.'
      : explain(chosen && chosen.why);
  }
  if (mcqNextEl) mcqNextEl.classList.remove('hidden');

  // Reading the steps first turns an objectively-graded question into a copying
  // exercise, so it doesn't get objective credit. `attemptFrom`'s docstring
  // already reserves 0.5 for "right after a hint".
  const peeked = typeof revealed === 'number' && revealed > 0;
  if (peeked) {
    recordAttempt(right ? 0.5 : 0, 'self', {});
  } else {
    recordAttempt(right ? 1 : 0, 'mcq', { k, miss: right ? null : (chosen && chosen.why) });
  }

  // The worked steps are the reward for having answered, either way.
  enableReveal();
}

/** The sentence for a wrong pick, or a plain fallback if none was declared. */
function explain(why) {
  const entry = why && typeof MISCONCEPTIONS !== 'undefined' ? MISCONCEPTIONS[why] : null;
  return entry && entry.hint
    ? entry.hint
    : 'Not quite — reveal the steps to see where it goes.';
}

if (mcqNextEl) {
  mcqNextEl.addEventListener('click', () => {
    if (typeof advance === 'function') advance();
  });
}

if (typeof module !== 'undefined' && module.exports) {
  module.exports = {
    MCQ_OPTIONS, buildChoices, normalLatex, numbersIn, shapeOf, equivalentAnswers,
  };
}
